import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Port from './port'
import Introduction from './Introduction'
import Work from './work'
import Contact from './contact'
import Side from './side'
import AOS from "aos";
import "aos/dist/aos.css";
import Spiner from '@/components/atoms/Spiner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    AOS.init();
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Port />
        <Introduction />
        <Work />
        <Side />
        <Contact setIsLoading={setIsLoading} />
        {isLoading && (<Spiner />)}
      </>
    </>
  )
}
