import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Port from './port'
import Introduction from './Introduction'
import Work from './work'
import Contact from './contact'
import Side from './side'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Port />
        <section>
          <Introduction />
        </section>
        <section>
          <Work />
        </section>
        <section>
          <Side />
        </section>
        <section>
          <Contact />
        </section>
      </div>
    </>
  )
}
